// AUTO-GENERATED by data_ingester_builder.ts
// Source table: Items

export const ITEMS_TABLE_NAME = "Items" as const;

export const ITEMS_COLUMNS = [
  "Item",
  "Category",
  "Genderlock",
  "Random",
  "Source",
] as const;

export type ItemsColumn = typeof ITEMS_COLUMNS[number];

export type ItemsRow = {
  Item: string;
  Category: string;
  Genderlock: string;
  Random: string;
  Source: string;
};

export type ItemsNice = {
  Item: string;
  Category: string;
  Genderlock: string;
  Random: boolean;
  Source: string;
};

export function toItemsNice(row: ItemsRow): ItemsNice {
  return {
    ...row,

    Random: row.Random.toLowerCase() === "true",
    Source: row.Source

  };
}