// AUTO-GENERATED by data_ingester_builder.ts
// Source table: Lucky

export const LUCKY_TABLE_NAME = "Lucky" as const;

export const LUCKY_COLUMNS = [
  "Original_Name",
  "Description",
  "Tarot",
  "Melee_Attack",
  "Ranged_Attack",
  "Melee_Damage",
  "Ranged_Damage",
  "Fortitude_Save",
  "Reflex_Save",
  "Will_Save",
  "AC",
  "Init",
  "HP",
  "Speed",
] as const;

export type LuckyColumn = typeof LUCKY_COLUMNS[number];

export type LuckyRow = {
  Original_Name: string;
  Description: string;
  Tarot: string;
  Melee_Attack: string;
  Ranged_Attack: string;
  Melee_Damage: string;
  Ranged_Damage: string;
  Fortitude_Save: string;
  Reflex_Save: string;
  Will_Save: string;
  AC: string;
  Init: string;
  HP: string;
  Speed: string;
};
