// AUTO-GENERATED by data_ingester_builder.ts
// Source table: Lucky

export const LUCKY_TABLE_NAME = "Lucky" as const;

export const LUCKY_COLUMNS = [
  "Original_Name",
  "Description",
  "Tarot",
  "Melee_Attack",
  "Ranged_Attack",
  "Melee_Damage",
  "Ranged_Damage",
  "Fortitude_Save",
  "Reflex_Save",
  "Will_Save",
  "AC",
  "Init",
  "HP",
  "Speed",
] as const;

export type LuckyColumn = typeof LUCKY_COLUMNS[number];

export type LuckyRow = {
  Original_Name: string;
  Description: string;
  Tarot: string;
  Melee_Attack: string;
  Ranged_Attack: string;
  Melee_Damage: string;
  Ranged_Damage: string;
  Fortitude_Save: string;
  Reflex_Save: string;
  Will_Save: string;
  AC: string;
  Init: string;
  HP: string;
  Speed: string;
};

export type LuckyNice = {
  Original_Name: string;
  Description: string;
  Tarot: string;

  Melee_Attack: number;
  Ranged_Attack: number;
  Melee_Damage: number;
  Ranged_Damage: number;

  Fortitude_Save: number;
  Reflex_Save: number;
  Will_Save: number;

  AC: number;
  Init: number;
  HP: number;
  Speed: number;
};

export function luckyRowToNice(row: LuckyRow): LuckyNice {
  return {
    ...row,

    Melee_Attack: Number(row.Melee_Attack),
    Ranged_Attack: Number(row.Ranged_Attack),
    Melee_Damage: Number(row.Melee_Damage),
    Ranged_Damage: Number(row.Ranged_Damage),

    Fortitude_Save: Number(row.Fortitude_Save),
    Reflex_Save: Number(row.Reflex_Save),
    Will_Save: Number(row.Will_Save),

    AC: Number(row.AC),
    Init: Number(row.Init),
    HP: Number(row.HP),
    Speed: Number(row.Speed),
  };
}