// AUTO-GENERATED by data_ingester_builder.ts
// Source table: names

export const NAMES_TABLE_NAME = "names" as const;

export const NAMES_COLUMNS = [
  "Name",
  "Type",
  "Group",
  "Source",
] as const;

export type NamesColumn = typeof NAMES_COLUMNS[number];

export type NamesRow = {
  Name: string;
  Type: string;
  Group: string;
  Source: string;
};
