// AUTO-GENERATED by data_ingester_builder.ts
// Source table: powers

export const POWERS_TABLE_NAME = "powers" as const;

export const POWERS_COLUMNS = [
  "Name",
  "Kind",
  "Tag",
  "Source",
  "variantOf",
] as const;

export type PowersColumn = typeof POWERS_COLUMNS[number];

export type PowersRow = {
  Name: string;
  Kind: string;
  Tag: string;
  Source: string;
  variantOf: string;
};
