// AUTO-GENERATED by data_ingester_builder.ts
// Source table: Professions

export const PROFESSIONS_TABLE_NAME = 'Professions' as const;

export const PROFESSIONS_COLUMNS = [
  'ProfessionTitle',
  'Genderlock',
  'TradeGood',
  'Weapon',
  'Source',
  'Race',
  'AdventurePack',
  'StartingFunds',
  'ArmorEquipped',
  'XCCPresentation',
] as const;

export type ProfessionsColumn = (typeof PROFESSIONS_COLUMNS)[number];

export type ProfessionsRow = {
  ProfessionTitle: string;
  Genderlock: string;
  TradeGood: string;
  Weapon: string;
  Source: string;
  Race: string;
  AdventurePack: string;
  StartingFunds: string;
  ArmorEquipped: string;
  XCCPresentation: string;
};

export type Profession = Omit<ProfessionsRow, 'StartingFunds'> & {
  StartingFunds: number;
};

export function toProfession(row: ProfessionsRow): Profession {
  return {
    ...row,
    StartingFunds: Number(row.StartingFunds),
  };
}
