// AUTO-GENERATED by data_ingester_builder.ts
// Source table: Professions

export const PROFESSIONS_TABLE_NAME = "Professions" as const;

export const PROFESSIONS_COLUMNS = [
  "ProfessionTitle",
  "Genderlock",
  "TradeGood",
  "Weapon",
  "Source",
] as const;

export type ProfessionsColumn = typeof PROFESSIONS_COLUMNS[number];

export type ProfessionsRow = {
  ProfessionTitle: string;
  Genderlock: string;
  TradeGood: string;
  Weapon: string;
  Source: string;
};
