// AUTO-GENERATED by data_ingester_builder.ts
// Source table: Weapons

export const WEAPONS_TABLE_NAME = "Weapons" as const;

export const WEAPONS_COLUMNS = [
  "Weapon",
  "WeaponType",
  "WeaponUnderlying",
  "WeaponDamageBase",
  "Genderlock",
  "Random",
  "Source",
] as const;

export type WeaponsColumn = typeof WEAPONS_COLUMNS[number];

export type WeaponsRow = {
  Weapon: string;
  WeaponType: string;
  WeaponUnderlying: string;
  WeaponDamageBase: string;
  Genderlock: string;
  Random: string;
  Source: string;
};

export type WeaponsNice = {
  Weapon: string;
  WeaponType: string;
  WeaponUnderlying: string;
  WeaponDamageBase: string;
  Genderlock: string;
  Random: boolean;
  Source: string;
};

export function toWeaponsNice(row: WeaponsRow): WeaponsNice {
  return {
    ...row,

    Random: row.Random.toLowerCase() === "true",
    Source: row.Source

  };
}