// AUTO-GENERATED by data_ingester_builder.ts
// Source table: Weapons

export const WEAPONS_TABLE_NAME = 'Weapons' as const;

export const WEAPONS_COLUMNS = [
  'Weapon',
  'WeaponType',
  'WeaponUnderlying',
  'WeaponDamageBase',
  'Genderlock',
  'RandomPool',
  'Source',
  'CommaSeparatedSpecialProperties',
  'Range',
] as const;

export type WeaponsColumn = (typeof WEAPONS_COLUMNS)[number];

export type WeaponsRow = {
  Weapon: string;
  WeaponType: string;
  WeaponUnderlying: string;
  WeaponDamageBase: string;
  Genderlock: string;
  RandomPool: string;
  Source: string;
  CommaSeparatedSpecialProperties: string;
  Range: string;
};

export type WeaponsNice = {
  Weapon: string;
  WeaponType: string;
  WeaponUnderlying: string;
  WeaponDamageBase: string;
  Genderlock: string;
  RandomPool: boolean;
  Source: string;
  CommaSeparatedSpecialProperties: string;
  Range: string;
};

export function toWeaponsNice(row: WeaponsRow): WeaponsNice {
  return {
    ...row,

    RandomPool: row.RandomPool.toLowerCase() === 'true',
    Source: row.Source,
  };
}
