// AUTO-GENERATED by data_ingester_builder.ts
// Source table: xcc_celebrity_headshots

export const XCC_CELEBRITY_HEADSHOTS_TABLE_NAME = 'xcc_celebrity_headshots' as const;

export const XCC_CELEBRITY_HEADSHOTS_COLUMNS = ['NAME', 'GENDER', 'HEADSHOT_URL'] as const;

export type XccCelebrityHeadshotsColumn = (typeof XCC_CELEBRITY_HEADSHOTS_COLUMNS)[number];

export type XccCelebrityHeadshotsRow = {
  NAME: string;
  GENDER: string;
  HEADSHOT_URL: string;
};
