// AUTO-GENERATED by data_ingester_builder.ts
// Source table: xcc_occupations

export const XCC_OCCUPATIONS_TABLE_NAME = "xcc_occupations" as const;

export const XCC_OCCUPATIONS_COLUMNS = [
  "Title",
  "Race",
  "TradeGood",
  "AdventurePack",
  "StartingFunds",
] as const;

export type XccOccupationsColumn = typeof XCC_OCCUPATIONS_COLUMNS[number];

export type XccOccupationsRow = {
  Title: string;
  Race: string;
  TradeGood: string;
  AdventurePack: string;
  StartingFunds: string;
};

export type XccOccupation = Omit<XccOccupationsRow, "StartingFunds"> & {
  StartingFunds: number;
};

export function toXccOccupation(row: XccOccupationsRow): XccOccupation {
  return {
    ...row,
    StartingFunds: Number(row.StartingFunds),
  };
}
