import seedrandom from "seedrandom";
import rawSystemPoints from "../../../swn_sector/system_points_of_interest.json";
import rawStarTypes from "../../../swn_sector/star_types.json";
import rawWorldAttributes from "../../../swn_sector/world_attributes_2.json";
import { generateSectorV3, type InhabitedWorldV2, type SectorV2Options, type StarSystemV3 } from "./sector_v2";

export type OrbitalPositionCategory = "TooHot" | "Goldilocks" | "TooCold_1" | "IngressEgress" | "TooCold_3";
export type ExtraWorldCategory = "TerrestrialPlanet" | "GasGiant" | "OtherObject";
export type PointOfInterestV4 = { id: string; kind: "Ingress Point" | "Egress Point" | "Other"; point: string; roll?: number; occupant?: string; situation?: string };
export type PlanetV4 = { id: string; name: string; archetype: string; category: "TerrestrialPlanet" };
export type PlanetDetailsV4 = Omit<InhabitedWorldV2["planetDetails"], "bulkComposition"> & { bulkComposition: Omit<InhabitedWorldV2["planetDetails"]["bulkComposition"], "color"> };
export type PrimaryPlanetV4 = PlanetV4 & Omit<InhabitedWorldV2, "id" | "name" | "order" | "orbitSlot" | "isPrimary" | "planetDetails"> & { kind: "PrimaryPlanet"; archetype: "PrimaryPlanet"; planetDetails: PlanetDetailsV4 };
export type SecondaryPlanetV4 = PlanetV4 & { kind: "SecondaryPlanet"; description: string; pointsOfInterest: PointOfInterestV4[] };
export type EmptyLocationV4 = { kind: "Empty" };
export type GasGiantLocationV4 = { kind: "GasGiant"; id: string; archetype: string; category: "GasGiant"; description: string; pointsOfInterest: PointOfInterestV4[]; satellites: Array<PrimaryPlanetV4 | SecondaryPlanetV4> };
export type OtherObjectLocationV4 = { kind: "OtherObject"; id: string; archetype: string; category: "OtherObject"; description: string; pointsOfInterest: PointOfInterestV4[] };
export type IndependentStationLocationV4 = { kind: "IndependentStation"; id: string; pointsOfInterest: [PointOfInterestV4] };
export type IngressEgressLocationV4 = { kind: "IngressEgress"; id: string; pointsOfInterest: [PointOfInterestV4, PointOfInterestV4] };
export type SystemLocationV4 = EmptyLocationV4 | PrimaryPlanetV4 | SecondaryPlanetV4 | GasGiantLocationV4 | OtherObjectLocationV4 | IndependentStationLocationV4 | IngressEgressLocationV4;
export type LocationSlotV4 = { id: string; orbitalPositionCategory: OrbitalPositionCategory; au: number; habitableSlot?: 1 | 2 | 3; location: SystemLocationV4 };
export type PrimaryStarV4 = { roll: number; result: string; hab: number; maxHabitableSlots: number };
export type StarSystemV4 = Omit<StarSystemV3, "worlds" | "primaryStar"> & { primaryStar: PrimaryStarV4; locationSlots: LocationSlotV4[] };
export type SectorV4 = { version: "v4"; seed: string; starCount: number; systems: StarSystemV4[] };

type RawArchetype = { archetype: string; description: string; category: ExtraWorldCategory };
type RawPoint = { roll: number; point: string; occupants: Array<{ roll: string; result: string }>; situations: Array<{ roll: string; result: string }> };
type RawStarType = { roll: number | string; result: string; hab: number; habitableSlots: number; orbitalZones: { tooHot: string; habitable: string | null; tooCold1: string; warpPoint: string; tooCold2: string; beyond: string } };
type V4Data = { orbitalPositionCategories: OrbitalPositionCategory[]; requiredLocations: Array<{ kind: "EgressIngressRegion"; orbitalPositionCategory: "IngressEgress" }>; extraWorlds: { countDice: "1d6"; minimumByOrbitalPosition: { TooHot: number; TooCold_1: number }; maximumByOrbitalPosition: { TooCold_3: number }; goldilocksOpenSlotExtraChance: number; eligibleArchetypes: string[]; allowedOrbitalPositionCategories: Record<string, OrbitalPositionCategory[]>; moonRules: { terrestrialExtraWorldMayOrbitGasGiant: boolean; terrestrialExtraWorldMoonChance: string; primaryPlanetMoonCreatesParentGasGiant: boolean; parentGasGiantMayUseGoldilocks: boolean } }; pointsOfInterest: { minimumIngressPoints: number; minimumEgressPoints: number; otherCountDice: "1d4+1"; independentOrbit: { kind: "IndependentOrbit"; createdByPoint: "Deep-space station"; onlyContainsPoint: "Deep-space station"; allowedOrbitalPositionCategories: Array<"TooHot" | "TooCold_1" | "TooCold_3"> } } };
const data = rawSystemPoints as { v4: V4Data; extraWorlds: { archetypes: RawArchetype[] }; otherPoint: { rows: RawPoint[] } };
const v4 = data.v4;
const starRows = (rawStarTypes as { tables: Array<{ id: string; rows: RawStarType[] }> }).tables.find(table => table.id === "star_type")?.rows ?? [];
const moonTable = (rawWorldAttributes as { tables: Array<{ id: string; dice: string; rows: Array<{ roll: number | string; result: "Yes" | "No" }> }> }).tables.find(table => table.id === "gas_giant_moon");
const archetypes = new Map(data.extraWorlds.archetypes.map(item => [item.archetype, item]));
const eligible = v4.extraWorlds.eligibleArchetypes.map(name => { const item = archetypes.get(name); if (item === undefined) throw new Error(`Missing archetype ${name}`); return item; });
const die = (rng: seedrandom.PRNG, sides: number) => Math.floor(rng() * sides) + 1;
const choose = <T>(rng: seedrandom.PRNG, values: readonly T[]): T => { if (values.length === 0) throw new Error("Cannot choose from empty values"); return values[die(rng, values.length) - 1]!; };
const matches = (roll: number, range: number | string) => { if (typeof range === "number") return roll === range; const [start, end = start] = range.split("-").map(Number); return roll >= start! && roll <= end!; };
function thermal(world: StarSystemV3["worlds"][number]): string { const value = world.attributes.temperature.thermalOrbit; if (value === undefined) throw new Error(`Missing thermal orbit for ${world.id}`); return value; }
function position(world: StarSystemV3["worlds"][number]): OrbitalPositionCategory { switch (thermal(world)) { case "Too Hot": return "TooHot"; case "Too Cold": return "TooCold_1"; case "Hot": case "Temperate": case "Cold": return "Goldilocks"; default: throw new Error(`Invalid thermal orbit for ${world.id}`); } }
export function preferredGoldilocksSlot(orbit: string): 1 | 2 | 3 | undefined { switch (orbit) { case "Hot": return 1; case "Temperate": return 2; case "Cold": return 3; case "Too Hot": case "Too Cold": return undefined; default: throw new Error(`Invalid thermal orbit ${orbit}`); } }
export function assignGoldilocksSlots(worlds: readonly { id: string; thermalOrbit: string }[], count: number): Map<string, 1 | 2 | 3> { const available = Array.from({ length: count }, (_, i) => i + 1); const result = new Map<string, 1 | 2 | 3>(); const candidates = worlds.map((world, index) => ({ world, index, preference: preferredGoldilocksSlot(world.thermalOrbit) })).filter((entry): entry is { world: { id: string; thermalOrbit: string }; index: number; preference: 1 | 2 | 3 } => entry.preference !== undefined).sort((a, b) => a.preference - b.preference || a.index - b.index); if (candidates.length > available.length) throw new Error("Insufficient Goldilocks slots"); for (const candidate of candidates) { const index = available.reduce((best, slot, i) => Math.abs(slot - candidate.preference) < Math.abs(available[best]! - candidate.preference) ? i : best, 0); result.set(candidate.world.id, available.splice(index, 1)[0]! as 1 | 2 | 3); } return result; }
function selectStar(rng: seedrandom.PRNG, system: StarSystemV3): StarSystemV3["primaryStar"] { const hab = Math.max(...system.worlds.map(world => world.calculatedHab)); const slots = system.worlds.filter(world => preferredGoldilocksSlot(thermal(world)) !== undefined).length; for (let tries = 0; tries < 10_000; tries += 1) { const roll = die(rng, 100); const row = starRows.find(item => matches(roll, item.roll)); if (row !== undefined && row.hab >= hab && row.habitableSlots >= slots) return { roll, result: row.result, hab: row.hab, habitableSlots: row.habitableSlots }; } throw new Error("Unable to select V4 star"); }
function allowed(archetype: RawArchetype): OrbitalPositionCategory[] { return v4.extraWorlds.allowedOrbitalPositionCategories[archetype.archetype] ?? v4.extraWorlds.allowedOrbitalPositionCategories[archetype.category] ?? []; }
function range(text: string): [number, number] { const values = text.match(/\d+(?:\.\d+)?/g)?.map(Number); if (values === undefined || values.length < 2) throw new Error(`Invalid AU range ${text}`); return [values[0]!, values[1]!]; }
function auRange(star: Pick<PrimaryStarV4, "roll" | "result">, category: OrbitalPositionCategory): [number, number] { const row = starRows.find(item => matches(star.roll, item.roll)); if (row === undefined) throw new Error(`Missing star row ${star.result}`); switch (category) { case "TooHot": return range(row.orbitalZones.tooHot); case "Goldilocks": if (row.orbitalZones.habitable === null) throw new Error(`${star.result} has no habitable range`); return range(row.orbitalZones.habitable); case "TooCold_1": return range(row.orbitalZones.tooCold1); case "IngressEgress": { const au = Number(row.orbitalZones.warpPoint.match(/\d+(?:\.\d+)?/)?.[0]); return [au, au]; } case "TooCold_3": return range(row.orbitalZones.tooCold2); } }
function primary(world: StarSystemV3["worlds"][number]): PrimaryPlanetV4 { const { order: _order, orbitSlot: _orbit, isPrimary: _primary, planetDetails, ...planet } = world; const { color: _color, ...bulkComposition } = planetDetails.bulkComposition; return { ...planet, kind: "PrimaryPlanet", archetype: "PrimaryPlanet", category: "TerrestrialPlanet", planetDetails: { ...planetDetails, bulkComposition } }; }
function secondary(id: string, archetype: RawArchetype): SecondaryPlanetV4 { return { kind: "SecondaryPlanet", id, name: archetype.archetype, archetype: archetype.archetype, category: "TerrestrialPlanet", description: archetype.description, pointsOfInterest: [] }; }
function fromArchetype(id: string, item: RawArchetype): SecondaryPlanetV4 | GasGiantLocationV4 | OtherObjectLocationV4 { if (item.category === "TerrestrialPlanet") return secondary(id, item); if (item.category === "GasGiant") return { kind: "GasGiant", id, archetype: item.archetype, category: "GasGiant", description: item.description, pointsOfInterest: [], satellites: [] }; return { kind: "OtherObject", id, archetype: item.archetype, category: "OtherObject", description: item.description, pointsOfInterest: [] }; }
function locations(slots: readonly LocationSlotV4[]): SystemLocationV4[] { const result: SystemLocationV4[] = []; for (const slot of slots) { result.push(slot.location); if (slot.location.kind === "GasGiant") result.push(...slot.location.satellites); } return result; }
function pointable(location: SystemLocationV4): location is SecondaryPlanetV4 | GasGiantLocationV4 | OtherObjectLocationV4 | IndependentStationLocationV4 | IngressEgressLocationV4 { return "pointsOfInterest" in location; }
function pointCandidates(row: RawPoint, slots: readonly LocationSlotV4[]): Array<SecondaryPlanetV4 | GasGiantLocationV4 | OtherObjectLocationV4> { const candidates = locations(slots).filter((location): location is SecondaryPlanetV4 | GasGiantLocationV4 | OtherObjectLocationV4 => location.kind === "SecondaryPlanet" || location.kind === "GasGiant" || location.kind === "OtherObject"); const filtered = row.point === "Asteroid base" || row.point === "Asteroid belt" ? candidates.filter(location => location.kind === "OtherObject" && location.archetype === "AsteroidBelt") : row.point === "Remote moon base" ? candidates.filter(location => location.kind === "SecondaryPlanet") : row.point === "Ancient orbital ruin" || row.point === "Research base" ? candidates.filter(location => location.kind === "SecondaryPlanet" || location.kind === "GasGiant") : candidates.filter(location => location.kind === "GasGiant"); return filtered.filter(location => location.kind !== "GasGiant" || !location.satellites.some(satellite => satellite.kind === "PrimaryPlanet")); }

function buildSystem(system: StarSystemV3, rng: seedrandom.PRNG): StarSystemV4 {
  const locationSlots: LocationSlotV4[] = []; let slotNo = 0; let locationNo = 0; let pointNo = 0;
  const slotId = () => `${system.id}-slot-${String(++slotNo).padStart(2, "0")}`; const locationId = () => `${system.id}-location-${String(++locationNo).padStart(2, "0")}`; const poi = (value: Omit<PointOfInterestV4, "id">): PointOfInterestV4 => ({ id: `${system.id}-poi-${String(++pointNo).padStart(2, "0")}`, ...value });
  const addSlot = (zone: OrbitalPositionCategory, location: SystemLocationV4, habitableSlot?: 1 | 2 | 3) => { const slot: LocationSlotV4 = { id: slotId(), orbitalPositionCategory: zone, au: 0, location, ...(habitableSlot === undefined ? {} : { habitableSlot }) }; locationSlots.push(slot); return slot; };
  const addPoi = (host: SystemLocationV4, value: Omit<PointOfInterestV4, "id">) => { if (!pointable(host)) throw new Error("Primary planets cannot have POIs"); const valueWithId = poi(value); host.pointsOfInterest.push(valueWithId); return valueWithId; };
  const goldilocks = assignGoldilocksSlots(system.worlds.map(world => ({ id: world.id, thermalOrbit: thermal(world) })), system.primaryStar.habitableSlots);
  for (const world of system.worlds) { const planet = primary(world); const zone = position(world); const habitableSlot = goldilocks.get(world.id); if (world.planetDetails.isGasGiantMoon && v4.extraWorlds.moonRules.primaryPlanetMoonCreatesParentGasGiant) addSlot(zone, { kind: "GasGiant", id: locationId(), archetype: "Jovian", category: "GasGiant", description: "H/He gas giant", pointsOfInterest: [], satellites: [planet] }, habitableSlot); else addSlot(zone, planet, habitableSlot); }
  const occupied = new Set(locationSlots.flatMap(slot => slot.habitableSlot === undefined ? [] : [slot.habitableSlot])); const open = Array.from({ length: system.primaryStar.habitableSlots }, (_, i) => (i + 1) as 1 | 2 | 3).filter(slot => !occupied.has(slot));
  if (open.length > 0 && rng() < v4.extraWorlds.goldilocksOpenSlotExtraChance) { const item = choose(rng, eligible.filter(value => value.category !== "OtherObject")); addSlot("Goldilocks", fromArchetype(locationId(), item), choose(rng, open)); }
  const transit: IngressEgressLocationV4 = { kind: "IngressEgress", id: locationId(), pointsOfInterest: [poi({ kind: "Ingress Point", point: "Ingress Point" }), poi({ kind: "Egress Point", point: "Egress Point" })] }; addSlot("IngressEgress", transit);
  const forced: OrbitalPositionCategory[] = [...Array(v4.extraWorlds.minimumByOrbitalPosition.TooHot).fill("TooHot"), ...Array(v4.extraWorlds.minimumByOrbitalPosition.TooCold_1).fill("TooCold_1")]; let outerCount = 0;
  for (let index = 0; index < Math.max(2, die(rng, 6)); index += 1) { const required = forced[index]; const item = choose(rng, required === undefined ? eligible.filter(value => allowed(value).some(zone => zone !== "TooCold_3" || outerCount < v4.extraWorlds.maximumByOrbitalPosition.TooCold_3)) : eligible.filter(value => allowed(value).includes(required))); const giantSlots = locationSlots.filter(slot => slot.location.kind === "GasGiant" && slot.orbitalPositionCategory !== "Goldilocks" && (slot.orbitalPositionCategory !== "TooCold_3" || outerCount < v4.extraWorlds.maximumByOrbitalPosition.TooCold_3)); const parent = required === undefined && item.category === "TerrestrialPlanet" && giantSlots.length > 0 && v4.extraWorlds.moonRules.terrestrialExtraWorldMayOrbitGasGiant && moonTable?.dice === "d100" && (() => { const roll = die(rng, 100); return moonTable.rows.find(row => matches(roll, row.roll))?.result === "Yes"; })() ? choose(rng, giantSlots) : undefined; const zone = parent?.orbitalPositionCategory ?? choose(rng, required === undefined ? allowed(item).filter(value => value !== "TooCold_3" || outerCount < v4.extraWorlds.maximumByOrbitalPosition.TooCold_3) : [required]); if (zone === "TooCold_3") outerCount += 1; if (parent?.location.kind === "GasGiant") parent.location.satellites.push(secondary(locationId(), item)); else addSlot(zone, fromArchetype(locationId(), item)); }
  for (let index = 0; index < die(rng, 4) + 1; index += 1) { const rows = data.otherPoint.rows.filter(row => row.point === "Deep-space station" || pointCandidates(row, locationSlots).length > 0); const row = choose(rng, rows); let host: SystemLocationV4; if (row.point === "Deep-space station") { const station: IndependentStationLocationV4 = { kind: "IndependentStation", id: locationId(), pointsOfInterest: [] as unknown as [PointOfInterestV4] }; addSlot(choose(rng, v4.pointsOfInterest.independentOrbit.allowedOrbitalPositionCategories), station); host = station; } else host = pointCandidates(row, locationSlots)[0]!; const point = addPoi(host, { kind: "Other", point: row.point, roll: row.roll, occupant: choose(rng, row.occupants).result, situation: choose(rng, row.situations).result }); if (host.kind === "IndependentStation") host.pointsOfInterest = [point]; }
  for (const zone of v4.orbitalPositionCategories) { const slots = locationSlots.filter(slot => slot.orbitalPositionCategory === zone); if (slots.length === 0) continue; const [minimum, maximum] = auRange(system.primaryStar, zone); slots.forEach((slot, index) => { slot.au = minimum + ((maximum - minimum) / slots.length) * (index + rng()); }); }
  locationSlots.sort((left, right) => left.au - right.au || left.id.localeCompare(right.id));
  const { worlds: _worlds, primaryStar, ...withoutWorlds } = system; return { ...withoutWorlds, primaryStar: { roll: primaryStar.roll, result: primaryStar.result, hab: primaryStar.hab, maxHabitableSlots: primaryStar.habitableSlots }, locationSlots };
}
export function generateSectorV4(seed: string, options: SectorV2Options = {}): SectorV4 { const v3 = generateSectorV3(seed, options); const rng = seedrandom(`${seed}:v4`); const systems = v3.systems.map(system => { const primaryStar = selectStar(rng, system); return buildSystem({ ...system, primaryStar, worlds: system.worlds.map(world => ({ ...world, planetDetails: { ...world.planetDetails, tidallyLocked: primaryStar.result === "M-type" || position(world) === "TooHot" } })) }, rng); }); return { version: "v4", seed, starCount: v3.starCount, systems }; }
export function isV4SystemValid(system: StarSystemV4): boolean { const slots = system.locationSlots; const all = locations(slots); const primaries = all.filter((location): location is PrimaryPlanetV4 => location.kind === "PrimaryPlanet"); const transit = all.filter((location): location is IngressEgressLocationV4 => location.kind === "IngressEgress"); const points = all.flatMap(location => pointable(location) ? location.pointsOfInterest : []); const extras = slots.filter(slot => slot.location.kind === "SecondaryPlanet" || slot.location.kind === "GasGiant" || slot.location.kind === "OtherObject"); const star = starRows.find(row => matches(system.primaryStar.roll, row.roll)); return primaries.length > 0 && primaries.every(planet => planet.tags.length === 2 && planet.planetDetails.bulkComposition.result.length > 0) && star?.result === system.primaryStar.result && system.primaryStar.hab >= Math.max(...primaries.map(planet => planet.calculatedHab)) && transit.length === 1 && transit[0]!.pointsOfInterest[0].kind === "Ingress Point" && transit[0]!.pointsOfInterest[1].kind === "Egress Point" && extras.length >= 2 && extras.length <= 7 && points.filter(point => point.kind === "Other").length >= 2 && points.filter(point => point.kind === "Other").length <= 5 && new Set(slots.map(slot => slot.id)).size === slots.length && slots.every(slot => slot.au >= 0) && slots.every((slot, index) => index === 0 || slots[index - 1]!.au <= slot.au) && new Set(slots.filter(slot => slot.habitableSlot !== undefined).map(slot => slot.habitableSlot)).size === slots.filter(slot => slot.habitableSlot !== undefined).length && slots.filter(slot => slot.habitableSlot !== undefined).every(slot => slot.habitableSlot! <= system.primaryStar.maxHabitableSlots) && all.filter(location => location.kind === "PrimaryPlanet").every(location => !("pointsOfInterest" in location)); }
